# Speak By Hand Model Creator

## Import Libraries

In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten, Conv1D, MaxPool1D, LSTM

from sklearn.metrics import classification_report

## Load Data

In [2]:
# gesture data directory
# mount to google drive first
# check repo for gdrive link of dataset
file_dir = "drive/MyDrive/data/"

## Preprocess Data

In [3]:
# get file names
file_names = os.listdir(file_dir)
file_names[:10]

['Down_2',
 'Down_4',
 'Down_14',
 'Down_3',
 'Down_19',
 'Down_7',
 'Down_11',
 'Down_12',
 'Down_15',
 'Down_1']

In [4]:
# will result to a list containing [Up, Down, Left, Right, Drink, ....]
file_name = []
for i in file_names:
  file_name.append(i.split("_")[0])

# create data frame out of the list
df = pd.DataFrame(file_name)
df.head()

0
0  Down
1  Down
2  Down
3  Down
4  Down

In [5]:
# convert categorical variable into dummy/indicator variables. This will be the labels.
y = pd.get_dummies(df)
y = np.array(y)
y[:]

array([[1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 1,

In [6]:
X = []

# columns for collected data
columns = ["Time", "a_X", "a_Y", "a_Z", "g_X", "g_Y", "g_Z"]

# extract data from dataset 
for file_name in file_names:
  data = pd.read_csv(f"{file_dir}{file_name}")
  data.columns = columns
  data.drop("Time", axis=1, inplace=True)
  X.append(data)
  
X = np.array(X)
X

array([[[-9.0021986e-01, -1.6759412e-02,  9.7611600e+00, -7.8190750e-02,
          6.2308256e-02,  4.5204030e-02],
        [-8.3318220e-01,  3.0885202e-01,  9.6294790e+00,  3.6651916e-03,
         -4.8869220e-03,  4.8869220e-02],
        [-8.5951840e-01,  7.9008654e-02,  9.7491890e+00,  2.4434610e-03,
          9.1629790e-02,  3.5430185e-02],
        ...,
        [ 1.0869676e+00, -1.8962077e+00,  9.2009170e+00,  6.4751714e-02,
         -2.8099802e-01, -3.0176744e-01],
        [ 2.3319526e+00, -1.5251064e+00,  9.6079310e+00,  2.3701571e-01,
         -5.3389620e-01, -3.5918877e-01],
        [ 2.9424740e+00, -1.5634137e+00,  8.8154510e+00, -4.6425760e-02,
         -4.7403142e-01, -3.7507126e-01]],

       [[-9.6965170e-01,  7.3741410e-01,  9.4331550e+00,  3.0543262e-02,
         -6.1086524e-02,  6.2308256e-02],
        [-9.0500826e-01,  1.0175357e+00,  9.1219080e+00, -1.7837265e-01,
         -9.2851520e-02,  8.1855945e-02],
        [-8.1642276e-01,  5.6024320e-01,  9.3278100e+00, -3.61632

In [7]:
# checks if every gesture data contains same no. of data points 
values = dict()
for x_s in X:
  leng = len(x_s)
  if leng in values:
     values[leng] += 1
  else:
     values[leng] = 1
values

{15: 100}

In [8]:
# split dataset into training and 'remaining data'
X_train, X_rem, y_train, y_rem = train_test_split(X, y, test_size=0.3, random_state=42)

# split remaining data into test and valid sets
X_valid, X_test, y_valid, y_test = train_test_split(X_rem, y_rem, test_size=0.5, random_state=42)

print(X_train.shape)
print(y_train.shape)
print("\n")

print(X_valid.shape)
print(y_valid.shape)
print("\n")

print(X_test.shape)
print(y_test.shape)

(70, 15, 6)
(70, 5)


(15, 15, 6)
(15, 5)


(15, 15, 6)
(15, 5)


## Build Model

In [9]:
def create_conv_model():
  model = tf.keras.Sequential()
  
  model.add(Conv1D(64, 3, input_shape=X.shape[1:]))
  model.add(Activation("relu"))
  model.add(MaxPool1D(pool_size=3))

  model.add(Conv1D(64, 2))
  model.add(Activation("relu"))
  model.add(MaxPool1D(pool_size=2))

  model.add(Flatten())
  model.add(Dense(64))

  model.add(Dense(5))
  model.add(Activation("softmax"))

  model.compile(optimizer='adam',
              loss = "categorical_crossentropy",
              metrics=['accuracy'])
  
  return model

In [10]:
def create_recurr_model():
  model = tf.keras.Sequential()

  model.add(LSTM(6, input_shape=X.shape[1:], return_sequences=True))
  model.add(Dropout(0.2))

  model.add(LSTM(6, input_shape=X.shape[1:], return_sequences=True))
  model.add(Dropout(0.2))

  model.add(LSTM(6, input_shape=X.shape[1:]))
  model.add(Dropout(0.2))

  model.add(Dense(32, activation="tanh"))
  model.add(Dropout(0.2))

  model.add(Dense(5, activation="softmax"))

  opt = tf.keras.optimizers.Adam(learning_rate=0.001, decay=1e-6)

  model.compile(optimizer=opt,
                loss = "categorical_crossentropy",
                metrics=['accuracy'])
  
  return model

In [11]:
# create convolution model
conv_model = create_conv_model()
conv_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, 13, 64)            1216      
                                                                 
 activation (Activation)     (None, 13, 64)            0         
                                                                 
 max_pooling1d (MaxPooling1D  (None, 4, 64)            0         
 )                                                               
                                                                 
 conv1d_1 (Conv1D)           (None, 3, 64)             8256      
                                                                 
 activation_1 (Activation)   (None, 3, 64)             0         
                                                                 
 max_pooling1d_1 (MaxPooling  (None, 1, 64)            0         
 1D)                                                    

In [12]:
# create recurrent model
recurr_model = create_recurr_model()
recurr_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 15, 6)             312       
                                                                 
 dropout (Dropout)           (None, 15, 6)             0         
                                                                 
 lstm_1 (LSTM)               (None, 15, 6)             312       
                                                                 
 dropout_1 (Dropout)         (None, 15, 6)             0         
                                                                 
 lstm_2 (LSTM)               (None, 6)                 312       
                                                                 
 dropout_2 (Dropout)         (None, 6)                 0         
                                                                 
 dense_2 (Dense)             (None, 32)               

## Train Model

In [13]:
early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=4)

In [14]:
# train convolution model
conv_model.fit(X_train, 
          y_train,
          epochs = 20, 
          validation_data = (X_valid, y_valid),
          callbacks=[early_stopping])

Epoch 1/20
3/3 [==============================] - 2s 212ms/step - loss: 1.7166 - accuracy: 0.2286 - val_loss: 1.2363 - val_accuracy: 0.4000
Epoch 2/20
3/3 [==============================] - 0s 22ms/step - loss: 1.2347 - accuracy: 0.5000 - val_loss: 1.0254 - val_accuracy: 0.5333
Epoch 3/20
3/3 [==============================] - 0s 36ms/step - loss: 1.1205 - accuracy: 0.4571 - val_loss: 0.9072 - val_accuracy: 0.7333
Epoch 4/20
3/3 [==============================] - 0s 21ms/step - loss: 0.9724 - accuracy: 0.6857 - val_loss: 0.8725 - val_accuracy: 0.8000
Epoch 5/20
3/3 [==============================] - 0s 44ms/step - loss: 0.9208 - accuracy: 0.6857 - val_loss: 0.8647 - val_accuracy: 0.6000
Epoch 6/20
3/3 [==============================] - 0s 33ms/step - loss: 0.8591 - accuracy: 0.7429 - val_loss: 0.7282 - val_accuracy: 1.0000
Epoch 7/20
3/3 [==============================] - 0s 26ms/step - loss: 0.7717 - accuracy: 0.9571 - val_loss: 0.6562 - val_accuracy: 0.9333
Epoch 8/20
3/3 [==========

In [15]:
# train recurrent model
recurr_model.fit(X_train, 
          y_train,
          epochs = 100,
          validation_data = (X_valid, y_valid),
          callbacks=[early_stopping])

Epoch 1/100
3/3 [==============================] - 15s 685ms/step - loss: 1.6132 - accuracy: 0.2286 - val_loss: 1.6300 - val_accuracy: 0.1333
Epoch 2/100
3/3 [==============================] - 0s 29ms/step - loss: 1.6143 - accuracy: 0.2429 - val_loss: 1.6228 - val_accuracy: 0.1333
Epoch 3/100
3/3 [==============================] - 0s 30ms/step - loss: 1.5940 - accuracy: 0.2571 - val_loss: 1.6151 - val_accuracy: 0.1333
Epoch 4/100
3/3 [==============================] - 0s 38ms/step - loss: 1.6018 - accuracy: 0.2857 - val_loss: 1.6077 - val_accuracy: 0.1333
Epoch 5/100
3/3 [==============================] - 0s 41ms/step - loss: 1.6134 - accuracy: 0.2143 - val_loss: 1.6003 - val_accuracy: 0.1333
Epoch 6/100
3/3 [==============================] - 0s 32ms/step - loss: 1.5773 - accuracy: 0.2857 - val_loss: 1.5925 - val_accuracy: 0.2000
Epoch 7/100
3/3 [==============================] - 0s 31ms/step - loss: 1.5803 - accuracy: 0.3000 - val_loss: 1.5844 - val_accuracy: 0.2667
Epoch 8/100
3/3 [=

## Test Model

In [16]:
# ---------- test convolution model -----------
conv_predictions = conv_model.predict(X_test)
conv_predictions[:5]

1/1 [==============================] - 0s 149ms/step


array([[2.9879328e-02, 8.3769039e-05, 1.6514826e-01, 2.7585002e-03,
        8.0213004e-01],
       [7.3628044e-01, 1.7721595e-03, 4.2851072e-02, 1.3209440e-01,
        8.7001853e-02],
       [6.9463767e-02, 2.0476559e-03, 7.2859615e-01, 2.0147981e-02,
        1.7974448e-01],
       [8.6289616e-03, 5.0703078e-03, 1.2885088e-04, 9.8592269e-01,
        2.4921336e-04],
       [7.3748493e-01, 3.4723396e-03, 1.7991148e-02, 2.1645515e-01,
        2.4596313e-02]], dtype=float32)

In [17]:
conv_prediction_classes = np.argmax(conv_predictions, axis=1)
conv_prediction_classes # predicted calsses

array([4, 0, 2, 3, 0, 0, 0, 3, 3, 4, 2, 3, 1, 1, 1])

In [18]:
conv_y_test_classes = np.argmax(y_test, axis=1)
conv_y_test_classes # actual classes

array([4, 0, 2, 3, 0, 0, 0, 3, 3, 4, 2, 3, 1, 1, 1])

In [19]:
print(classification_report(conv_y_test_classes, conv_prediction_classes))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         2

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



In [20]:
# ---------- test recurrent model ----------
recurr_predictions = recurr_model.predict(X_test)
recurr_predictions[:5]

1/1 [==============================] - 2s 2s/step


array([[2.1474935e-01, 9.7702323e-03, 4.5145009e-02, 6.4814076e-02,
        6.6552138e-01],
       [4.4388106e-01, 3.7037598e-03, 6.9486676e-03, 3.5441673e-01,
        1.9104965e-01],
       [2.3398737e-03, 1.0415616e-02, 9.2519492e-01, 5.9175404e-04,
        6.1457902e-02],
       [3.4484565e-01, 1.2698821e-03, 1.2341895e-03, 6.1528951e-01,
        3.7360661e-02],
       [4.4369510e-01, 3.7768590e-03, 6.9363401e-03, 3.5671195e-01,
        1.8887965e-01]], dtype=float32)

In [21]:
recurr_prediction_classes = np.argmax(recurr_predictions, axis=1)
recurr_prediction_classes # predicted calsses

array([4, 0, 2, 3, 0, 4, 3, 3, 3, 4, 2, 3, 1, 1, 1])

In [22]:
recurr_y_test_classes = np.argmax(y_test, axis=1)
recurr_y_test_classes # actual classes

array([4, 0, 2, 3, 0, 0, 0, 3, 3, 4, 2, 3, 1, 1, 1])

In [23]:
print(classification_report(recurr_y_test_classes, recurr_prediction_classes))

              precision    recall  f1-score   support

           0       1.00      0.50      0.67         4
           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         2
           3       0.80      1.00      0.89         4
           4       0.67      1.00      0.80         2

    accuracy                           0.87        15
   macro avg       0.89      0.90      0.87        15
weighted avg       0.90      0.87      0.85        15



## Export Model to TFLite

In [24]:
conv_model_directory = "./ConvGestureModel"
conv_model.save(conv_model_directory)

In [25]:
# Necessary for RNN models
run_model = tf.function(lambda x: recurr_model(x))

BATCH_SIZE = 1
STEPS = 15
INPUT_SIZE = 6
concrete_func = run_model.get_concrete_function(tf.TensorSpec([BATCH_SIZE, STEPS, INPUT_SIZE], recurr_model.inputs[0].dtype))

recurr_model_directory = "./RecurrGestureModel"
recurr_model.save(recurr_model_directory, save_format="tf", signatures=concrete_func)

In [26]:
# Convert the models
converter = tf.lite.TFLiteConverter.from_saved_model(conv_model_directory) # path to the SavedModel directory
conv_tflite_model = converter.convert()

converter = tf.lite.TFLiteConverter.from_saved_model(recurr_model_directory) 
recurr_tflite_model = converter.convert()

# Save the models
with open('gesture_conv_model.tflite', 'wb') as f:
  f.write(conv_tflite_model)

with open('gesture_recurr_model.tflite', 'wb') as f:
  f.write(recurr_tflite_model)